build (gcc):
  stage: build
  image: gcc
  before_script:
    - apt update && apt -y install libnlopt-cxx-dev
  script:
    - make
    - make lib
    - make examples/m2
    - make examples/m2cons
    - make examples/m2ccons
    - make examples/m2vertex
    - make examples/m2consvertex
    - make examples/m2vertex_ineq
    - make examples/m2consvertex_ineq
    - DESTDIR="$PWD/pkg" make install
    - ls -R "$PWD/pkg"

build (clang):
  stage: build
  image: ubuntu:20.04
  before_script:
    - apt update && apt -y install build-essential clang libnlopt-cxx-dev
  script:
    - CXX=clang++ make
    - CXX=clang++ make lib
    - CXX=clang++ make examples/m2
    - CXX=clang++ make examples/m2cons
    - CXX=clang++ make examples/m2ccons
    - CXX=clang++ make examples/m2vertex
    - CXX=clang++ make examples/m2consvertex
    - CXX=clang++ make examples/m2vertex_ineq
    - CXX=clang++ make examples/m2consvertex_ineq
    - DESTDIR="$PWD/pkg" make install
    - ls -R "$PWD/pkg"
