image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install libnlopt-cxx-dev
  script:
    - make
    - make lib
    - make examples/m2
    - make examples/m2cons
    - make examples/m2ccons
    - make exmaples/m2vertex
    - make exmaples/m2consvertex
    - DESTDIR="$PWD/pkg" make install
    - ls -R "$PWD/pkg"
