language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup

addons:
  apt:
    packages: libnlopt-dev
  homebrew:
    packages: nlopt
    update: true

script:
  - make
  - make lib
  - make examples/m2
  - make examples/m2cons
  - DESTDIR="$PWD/pkg" make install
  - ls -R "$PWD/pkg"
